/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pedrapapeltesoura;

import java.awt.event.ActionListener;
import javax.accessibility.AccessibleContext;
import javax.swing.JRadioButton;

/**
 *
 * @author 927182
 */
public class PedraPapelTesoura extends javax.swing.JFrame {

    /**
     * Creates new form PedraPapelTesoura
     */
    public PedraPapelTesoura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jrbPedra = new javax.swing.JRadioButton();
        jrbPapel = new javax.swing.JRadioButton();
        jrbTesoura = new javax.swing.JRadioButton();
        JLREsultado = new javax.swing.JLabel();
        JBEvento = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        buttonGroup2.add(jrbPedra);
        jrbPedra.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jrbPedra.setText("Pedra");
        jrbPedra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbPedraActionPerformed(evt);
            }
        });

        buttonGroup2.add(jrbPapel);
        jrbPapel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jrbPapel.setText("Papel");
        jrbPapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbPapelActionPerformed(evt);
            }
        });

        buttonGroup2.add(jrbTesoura);
        jrbTesoura.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jrbTesoura.setText("Tesoura");
        jrbTesoura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbTesouraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbTesoura)
                    .addComponent(jrbPapel)
                    .addComponent(jrbPedra))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jrbPedra)
                .addGap(18, 18, 18)
                .addComponent(jrbPapel)
                .addGap(18, 18, 18)
                .addComponent(jrbTesoura)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        JLREsultado.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        JLREsultado.setText(" ");
        JLREsultado.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                JLREsultadoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        JBEvento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JBEvento.setText("GO");
        JBEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBEventoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 36, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(JBEvento)
                        .addGap(180, 180, 180))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(JLREsultado, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JBEvento)
                .addGap(18, 18, 18)
                .addComponent(JLREsultado)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Pedra, Papel ou Tesoura?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JBEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBEventoActionPerformed
      
       boolean pedra = jrbPedra.isSelected();
       boolean papel = jrbPapel.isSelected();
       boolean tesoura = jrbTesoura.isSelected();
        
                
        boolean iAPedra = false;
        boolean iAPapel = false;
        boolean iATesoura = false;
        
        // I.A \/
        
        int num = (int) (Math.random() * 3);
        
        System.out.println(num);
        
        switch (num) {
            case 0:
                iAPedra = true;
                break;
                
            case 1:
                iAPapel = true;
                break;
                
            case 2:
                iATesoura = true;
                break;
            default:
                throw new AssertionError();
        }
       
        //verificação \/
        
        System.out.println(pedra);
        System.out.println(papel);
        System.out.println(tesoura);
        System.out.println("-------------");
        System.out.println(iAPedra);
        System.out.println(iAPapel);
        System.out.println(iATesoura);

        if(pedra == true){
            if(iAPedra == true){
                JLREsultado.setText("Jogador Empatou.");
            }else if(iAPapel == true){
                JLREsultado.setText("Jogador perdeu!");
            }else if(iATesoura == true){
                JLREsultado.setText("Jogador venceu.");
            }
        }else if(papel == true && pedra == false && tesoura == false){
            if(iAPapel == false){
                JLREsultado.setText("Jogador Empatou.");
            }else if(iAPedra == false){
                JLREsultado.setText("Jogador perdeu!!");
            }else if(iATesoura == false){
                JLREsultado.setText("Jogador venceu.");
            }
        }else if(tesoura == true && papel == false && pedra == false){
            if(iATesoura == true){
                JLREsultado.setText("Jogador Empatou.");
            }else if(iAPedra == true){
                JLREsultado.setText("Jogador perdeu!");
            }else if(iAPapel == true){
                JLREsultado.setText("Jogador venceu.");
            }
        }  
    }//GEN-LAST:event_JBEventoActionPerformed

    private void JLREsultadoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_JLREsultadoAncestorAdded

    }//GEN-LAST:event_JLREsultadoAncestorAdded
        
    private void jrbTesouraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbTesouraActionPerformed
//        JRadioButton jTesoura = new JRadioButton("true");
//        boolean tesoura = Boolean.parseBoolean(jTesoura.getText());
    }//GEN-LAST:event_jrbTesouraActionPerformed

    private void jrbPapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbPapelActionPerformed
//        JRadioButton jPapel = new JRadioButton("true");
//        boolean papel = Boolean.parseBoolean(jPapel.getText());
    }//GEN-LAST:event_jrbPapelActionPerformed

    private void jrbPedraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbPedraActionPerformed
//        JRadioButton jPedra = new JRadioButton("true");
//        boolean pedra = Boolean.parseBoolean(jPedra.getText());
    }//GEN-LAST:event_jrbPedraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PedraPapelTesoura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PedraPapelTesoura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PedraPapelTesoura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PedraPapelTesoura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PedraPapelTesoura().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBEvento;
    private javax.swing.JLabel JLREsultado;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jrbPapel;
    private javax.swing.JRadioButton jrbPedra;
    private javax.swing.JRadioButton jrbTesoura;
    // End of variables declaration//GEN-END:variables
}
